[package]
name = "puzzle_game"
version = "0.1.0"
authors = ["Nathan Stocks <nathan@agileperception.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
puzzles = { path = "../puzzles" }
log = "0.4"
env_logger = "0.9"
